# Generated by Django 5.2 on 2025-04-10 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='sportfacility',
            name='slot_duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('facility', 'date', 'start_time')},
        ),
    ]
