# Generated by Django 5.2 on 2025-04-13 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_timeslot_options_reservation_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportfacility',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='sportfacility',
            name='opening_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
