# Generated by Django 5.2 on 2025-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_court_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('court', 'date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('time_slot',)},
        ),
    ]
