# Generated by Django 5.2 on 2025-04-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
