# Generated by Django 5.2 on 2025-04-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_facility_field'),
        ('reservations', '0006_alter_reservation_unique_together'),
    ]

    operations = [
    ]
